SELECT * FROM customer_shopping.customer;
-- What is the total revenue generated by male and females customers? 
select gender,sum(purchase_amount) as total_revenue from customer_shopping.customer group by gender;
-- Which customer used a discount but still spent more than average purchase amount ?
-- select avg(purchase_amount) as avg_purchase_amount from customer_shopping.customer;
select customer_id,purchase_amount from customer_shopping.customer 
where discount_applied='Yes' and 
purchase_amount > (select avg(purchase_amount) as avg_purchase_amount from customer_shopping.customer);
-- Which are the top 5 products with the highest average review rating?
select item_purchased,avg(review_rating) as 'Average Review Rating'
from customer_shopping.customer
group by item_purchased
order by avg(review_rating) desc 
limit 5 ;
-- Compare the average purchase amount between standard and express shipping ?
select shipping_type,avg(purchase_amount)
from customer_shopping.customer
where shipping_type in ('Express','Standard')
group by shipping_type;
-- Do subscribed customer spent more ?Compare average apent and total revenue between subscribers 
-- and non subscribers?
select subscription_status,
count(customer_id) as 'Total_customers',
round(avg(purchase_amount),2) as 'average_spent',
sum(purchase_amount) as 'total_revenue'
from customer_shopping.customer
group by subscription_status;
-- Which 5 products have the highest percentage of purchase with discount applied?
select item_purchased,
round((sum(case when discount_applied = 'Yes' then 1 else 0 end )/count(*))*100,2) as percentage
from customer_shopping.customer
group by item_purchased
order by percentage desc
limit 5;
-- Segment customer into New,Returning,and loyal based on their total purchase and show the count
-- of each segment?
with customer_type as (
select customer_id,previous_purchases,
case
    when previous_purchases=1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as segment_customer 
from customer_shopping.customer
)
select segment_customer,count(segment_customer) as count 
from customer_type
group by segment_customer;
-- Are customers who are repeat buyers(more than 5 times) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping.customer
where previous_purchases>5
group by subscription_status;
-- What is the revenue contibution of each age group ?
select age_group,
sum(purchase_amount) as revenue_contribution 
from customer_shopping.customer
group by age_group
order by revenue_contribution desc;

   